[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Christian Adåker <cadaker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day01"

[[bin]]
name = "day02"

[dependencies]
regex = "1.10.2"
